<?php
/**
 * Public authentication/profile bridge.
 *
 * The BDC owns presentation composition, but does not reimplement the Entra
 * authentication protocol. When the Gateway shortcode is available, it is the
 * preferred runtime integration.
 *
 * @package BDC_Knowledge_Base
 */

namespace BDC\KnowledgeBase;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Public_Auth_Bridge {

	private const ENTRA_SHORTCODE = 'bdc_entra_login';
	private static ?string $gateway_markup = null;

	/**
	 * Resolve the Gateway shortcode during enqueue time as well as render time.
	 * This gives integrations that enqueue their own assets a normal WP lifecycle.
	 */
	public static function prime(): void {
		self::gateway_markup();
	}

	public static function render(): void {
		$gateway = self::gateway_markup();
		if ( '' !== $gateway ) {
			echo '<div class="bdc-public-auth bdc-public-auth--gateway">';
			// Trusted integration markup generated by the installed Entra Gateway.
			echo $gateway; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			echo '</div>';
			return;
		}

		self::render_wordpress_fallback();
	}

	public static function gateway_available(): bool {
		return shortcode_exists( self::ENTRA_SHORTCODE );
	}

	private static function gateway_markup(): string {
		if ( null !== self::$gateway_markup ) {
			return self::$gateway_markup;
		}
		self::$gateway_markup = '';

		if ( ! self::gateway_available() ) {
			return '';
		}

		$markup = do_shortcode( '[' . self::ENTRA_SHORTCODE . ' mode="profile-menu" show_department="true" show_job_title="true" show_logout="true" show_admin_link="auto"]' );
		self::$gateway_markup = is_string( $markup ) ? trim( $markup ) : '';
		return self::$gateway_markup;
	}

	private static function render_wordpress_fallback(): void {
		if ( ! is_user_logged_in() ) {
			echo '<a class="bdc-public-auth__login" href="' . esc_url( wp_login_url( self::current_url() ) ) . '">';
			echo '<span class="dashicons dashicons-admin-users" aria-hidden="true"></span>';
			echo '<span>' . esc_html__( 'Entrar', 'bdc-knowledge-base' ) . '</span>';
			echo '</a>';
			return;
		}

		$user = wp_get_current_user();
		$name = $user instanceof \WP_User ? (string) $user->display_name : '';
		if ( '' === trim( $name ) ) {
			$name = __( 'Usuário', 'bdc-knowledge-base' );
		}

		echo '<details class="bdc-public-account">';
		echo '<summary>';
		echo '<span class="bdc-public-account__avatar" aria-hidden="true">' . esc_html( self::initials( $name ) ) . '</span>';
		echo '<span class="bdc-public-account__name">' . esc_html( $name ) . '</span>';
		echo '<span class="dashicons dashicons-arrow-down-alt2" aria-hidden="true"></span>';
		echo '</summary>';
		echo '<div class="bdc-public-account__menu">';
		echo '<a href="' . esc_url( admin_url( 'profile.php' ) ) . '">' . esc_html__( 'Meu perfil', 'bdc-knowledge-base' ) . '</a>';
		echo '<a href="' . esc_url( wp_logout_url( home_url( '/' ) ) ) . '">' . esc_html__( 'Sair', 'bdc-knowledge-base' ) . '</a>';
		echo '</div>';
		echo '</details>';
	}

	private static function current_url(): string {
		$scheme = is_ssl() ? 'https://' : 'http://';
		$host = isset( $_SERVER['HTTP_HOST'] ) && is_scalar( $_SERVER['HTTP_HOST'] )
			? sanitize_text_field( wp_unslash( (string) $_SERVER['HTTP_HOST'] ) )
			: '';
		$uri = isset( $_SERVER['REQUEST_URI'] ) && is_scalar( $_SERVER['REQUEST_URI'] )
			? wp_unslash( (string) $_SERVER['REQUEST_URI'] )
			: '/';
		return '' !== $host ? $scheme . $host . $uri : home_url( '/' );
	}

	private static function initials( string $name ): string {
		$parts = preg_split( '/\s+/u', trim( $name ), -1, PREG_SPLIT_NO_EMPTY );
		if ( empty( $parts ) ) {
			return 'U';
		}

		$char = static function ( string $value ): string {
			return function_exists( 'mb_substr' ) ? mb_substr( $value, 0, 1 ) : substr( $value, 0, 1 );
		};
		$upper = static function ( string $value ): string {
			return function_exists( 'mb_strtoupper' ) ? mb_strtoupper( $value ) : strtoupper( $value );
		};

		$first = $char( (string) $parts[0] );
		$last = count( $parts ) > 1 ? $char( (string) $parts[ count( $parts ) - 1 ] ) : '';
		return $upper( $first . $last );
	}
}